import { Clip, TranscriptGroup } from './types';

export const MOCK_ANALYSIS_CLIPS: Clip[] = [
  {
    id: 'c1', number: 1,
    title: 'El secreto del éxito en marketing digital',
    score: 9.4,
    hook: '¿Sabías que el 90% de las startups fallan por esta razón que nadie te cuenta?',
    category: 'Educativo',
    startMinutes: 2, startSeconds: 15, endMinutes: 3, endSeconds: 45,
    justification: 'Gancho de curiosidad muy fuerte + estadística impactante + solución práctica al final. Estructura perfecta para viralizarse en TikTok.',
    selected: false,
  },
  {
    id: 'c2', number: 2,
    title: 'Anécdota del primer cliente',
    score: 8.8,
    hook: 'Nuestro primer cliente nos pagó con una pizza y un apretón de manos...',
    category: 'Storytelling',
    startMinutes: 10, startSeconds: 45, endMinutes: 12, endSeconds: 10,
    justification: 'Momento emocional y relatable. Las historias de origen conectan profundamente con audiencias emprendedoras y generan alto engagement.',
    selected: false,
  },
  {
    id: 'c3', number: 3,
    title: 'Las 3 herramientas de IA que uso cada día',
    score: 8.1,
    hook: 'Si tuviera que elegir solo 3 herramientas de IA para mi negocio, elegiría estas...',
    category: 'Tech',
    startMinutes: 22, startSeconds: 10, endMinutes: 23, endSeconds: 40,
    justification: 'Contenido de tipo listicle con IA como tema. Alto potencial de guardado y compartido. Muy alineado con LinkedIn.',
    selected: false,
  },
  {
    id: 'c4', number: 4,
    title: 'La mentalidad de los que fracasan',
    score: 7.6,
    hook: 'La única diferencia entre los que triunfan y los que fracasan no es el dinero ni los contactos...',
    category: 'Inspiracional',
    startMinutes: 31, startSeconds: 0, endMinutes: 32, endSeconds: 20,
    justification: 'Desafía creencias comunes con una perspectiva contraintuitiva. Genera debate en los comentarios.',
    selected: false,
  },
  {
    id: 'c5', number: 5,
    title: 'Cómo conseguí mis primeros 1000 clientes',
    score: 7.2,
    hook: 'Cero presupuesto de marketing. Solo esta estrategia que cualquiera puede replicar.',
    category: 'Educativo',
    startMinutes: 38, startSeconds: 30, endMinutes: 40, endSeconds: 0,
    justification: 'Prueba social + promesa de replicabilidad. Muy alineado con audiencias de emprendimiento.',
    selected: false,
  },
];

export const MOCK_TRANSCRIPT: TranscriptGroup[] = [
  {
    speaker: 'Speaker A',
    speakerColor: 'primary',
    lines: [
      { time: '00:00', text: 'Bienvenidos a El Futuro Hoy. Soy Carlos y hoy tenemos un episodio que os va a cambiar la perspectiva sobre el emprendimiento digital.' },
      { time: '00:15', text: 'Mi invitado de hoy ha construido tres empresas desde cero, dos de ellas superando el millón de usuarios.' },
    ],
  },
  {
    speaker: 'Speaker B',
    speakerColor: 'secondary',
    lines: [
      { time: '00:35', text: 'Gracias Carlos, es un placer. Y sí, suena bien dicho así, pero hubo muchos fracasos en el camino.' },
      { time: '00:45', text: 'El primero que me viene a la mente es que intentamos escalar sin tener retención. Crecimos rápido y caímos más rápido.' },
    ],
  },
  {
    speaker: 'Speaker A',
    speakerColor: 'primary',
    lines: [
      { time: '02:10', text: 'Cuéntanos, ¿cuál es el error número uno que ves repetirse en startups que no sobreviven?', clipId: 'c1' },
      { time: '02:20', text: 'Porque hay una estadística brutal que compartiste antes de empezar la grabación...' },
    ],
  },
  {
    speaker: 'Speaker B',
    speakerColor: 'secondary',
    lines: [
      { time: '02:30', text: 'El 90% de startups fallan porque construyen un producto que nadie quiere. No es falta de dinero, ni de tecnología.', clipId: 'c1' },
      { time: '02:42', text: 'Hacen product development en vez de customer development. Es sutil pero es la diferencia entre sobrevivir o no.' },
      { time: '02:55', text: 'Nosotros lo hicimos en nuestra primera empresa. Pasamos 8 meses construyendo algo que el mercado no necesitaba.' },
    ],
  },
  {
    speaker: 'Speaker A',
    speakerColor: 'primary',
    lines: [
      { time: '10:30', text: 'Y cuándo conseguiste tu primer cliente real, ¿cómo fue esa experiencia?', clipId: 'c2' },
    ],
  },
  {
    speaker: 'Speaker B',
    speakerColor: 'secondary',
    lines: [
      { time: '10:45', text: 'Fue... surrealista. Nos pagaron con una pizza y un apretón de manos. Literalmente.', clipId: 'c2' },
      { time: '10:58', text: 'Éramos tres en un piso compartido en Madrid, sin dinero, y ese pequeño gesto nos dio energía para seis meses más.' },
      { time: '11:15', text: 'A veces el primer pago no es económico. Es la validación de que tu solución tiene valor para alguien real.' },
    ],
  },
  {
    speaker: 'Speaker A',
    speakerColor: 'primary',
    lines: [
      { time: '22:05', text: 'Hablemos de herramientas. ¿Qué stack usas hoy con IA para tu día a día?', clipId: 'c3' },
    ],
  },
  {
    speaker: 'Speaker B',
    speakerColor: 'secondary',
    lines: [
      { time: '22:10', text: 'Si tuviera que quedarme con tres... primero Claude para todo lo que es razonamiento complejo y escritura.', clipId: 'c3' },
      { time: '22:25', text: 'Segundo, Cursor para programar, aunque no soy programador. Me permite construir prototipos yo solo.' },
      { time: '22:40', text: 'Y tercero, Perplexity para investigación. Ha reemplazado completamente mi uso de Google Search.' },
    ],
  },
  {
    speaker: 'Speaker A',
    speakerColor: 'primary',
    lines: [
      { time: '25:00', text: 'Cambiando de tema. Hablemos de mentalidad. ¿Qué diferencia ves entre los que triunfan y los que no?' },
      { time: '25:15', text: 'Porque hay mucha gente con talento que no logra despegar.' },
    ],
  },
  {
    speaker: 'Speaker B',
    speakerColor: 'secondary',
    lines: [
      { time: '25:30', text: 'Mira, la diferencia no es el talento, ni los contactos, ni siquiera el dinero.' },
      { time: '25:45', text: 'Es la capacidad de ejecutar cuando no tienes ganas. Punto. Eso separa al 90% del 10%.' },
      { time: '26:10', text: 'Yo he visto gente brillante que nunca lanza nada. Y gente promedio que lanza cada semana.' },
      { time: '26:30', text: '¿Quién gana a largo plazo? Siempre los que ejecutan.' },
    ],
  },
  {
    speaker: 'Speaker A',
    speakerColor: 'primary',
    lines: [
      { time: '28:00', text: 'Eso me lleva a la siguiente pregunta. ¿Cómo manejas el fracaso?' },
    ],
  },
  {
    speaker: 'Speaker B',
    speakerColor: 'secondary',
    lines: [
      { time: '28:15', text: 'El fracaso es información. Nada más. Cada vez que algo no funciona, aprendes qué no hacer.' },
      { time: '28:30', text: 'Mi segundo negocio fue un desastre total. Perdimos todo el dinero en seis meses.' },
      { time: '28:50', text: 'Pero de ahí salió la idea para el tercero, que fue el que realmente funcionó.' },
      { time: '29:10', text: 'Si no hubiéramos fracasado tan estrepitosamente, jamás habríamos pivotado a ese modelo.' },
    ],
  },
  {
    speaker: 'Speaker A',
    speakerColor: 'primary',
    lines: [
      { time: '31:00', text: 'Cuéntanos ese pivote. ¿Qué cambió exactamente?', clipId: 'c4' },
    ],
  },
  {
    speaker: 'Speaker B',
    speakerColor: 'secondary',
    lines: [
      { time: '31:10', text: 'La única diferencia entre los que triunfan y los que fracasan no es el dinero ni los contactos.', clipId: 'c4' },
      { time: '31:25', text: 'Es la velocidad a la que iteran. Nosotros pasamos de lanzar una vez al trimestre a lanzar cada semana.' },
      { time: '31:45', text: 'Eso nos permitió aprender 12 veces más rápido que la competencia.' },
      { time: '32:05', text: 'Y al cabo de un año teníamos un producto que el mercado realmente quería.' },
    ],
  },
  {
    speaker: 'Speaker A',
    speakerColor: 'primary',
    lines: [
      { time: '34:00', text: '¿Y qué papel juega el equipo en todo esto?' },
      { time: '34:10', text: 'Porque mucha gente intenta hacerlo todo solo.' },
    ],
  },
  {
    speaker: 'Speaker B',
    speakerColor: 'secondary',
    lines: [
      { time: '34:25', text: 'El equipo lo es todo. Yo no sé programar, no sé diseñar. Mi superpoder es rodearme de gente mejor que yo.' },
      { time: '34:45', text: 'La clave es encontrar personas que complementen tus debilidades y compartir equity con generosidad.' },
      { time: '35:05', text: 'Un 100% de nada vale cero. Pero un 30% de algo grande vale mucho.' },
    ],
  },
  {
    speaker: 'Speaker A',
    speakerColor: 'primary',
    lines: [
      { time: '38:00', text: 'Bueno, y para cerrar... cuéntanos la historia de los primeros 1000 clientes.', clipId: 'c5' },
      { time: '38:15', text: 'Porque sé que lo hicisteis con presupuesto cero.' },
    ],
  },
  {
    speaker: 'Speaker B',
    speakerColor: 'secondary',
    lines: [
      { time: '38:30', text: 'Cero presupuesto de marketing. Solo esta estrategia que cualquiera puede replicar.', clipId: 'c5' },
      { time: '38:45', text: 'Nos metimos en comunidades de Reddit, Indie Hackers, Twitter... y simplemente ayudamos.' },
      { time: '39:05', text: 'No vendíamos nada. Respondíamos preguntas, compartíamos código, dábamos feedback gratuito.' },
      { time: '39:25', text: 'Al cabo de 3 meses, la gente nos buscaba a nosotros. No teníamos que perseguir a nadie.' },
      { time: '39:50', text: 'Es la estrategia de dar primero. Suena simple pero casi nadie lo hace con consistencia.' },
    ],
  },
  {
    speaker: 'Speaker A',
    speakerColor: 'primary',
    lines: [
      { time: '41:00', text: '¿Algún consejo final para alguien que está empezando hoy?' },
    ],
  },
  {
    speaker: 'Speaker B',
    speakerColor: 'secondary',
    lines: [
      { time: '41:15', text: 'Sí. Deja de planificar y empieza a hacer. Tu primer producto será horrible, y eso está bien.' },
      { time: '41:35', text: 'El mercado te va a decir qué necesita si le escuchas. Pero tienes que estar en el mercado primero.' },
      { time: '41:55', text: 'Y no compares tu capítulo 1 con el capítulo 20 de otra persona. Cada historia tiene su ritmo.' },
    ],
  },
  {
    speaker: 'Speaker A',
    speakerColor: 'primary',
    lines: [
      { time: '43:00', text: 'Increíble. Muchas gracias por compartir todo esto con nosotros.' },
      { time: '43:15', text: 'Para los que nos escuchan, dejen sus comentarios y nos vemos en el próximo episodio.' },
      { time: '43:30', text: '¡Hasta la próxima!' },
    ],
  },
];

export const MOCK_LIBRARY_CLIPS: Clip[] = [
  {
    id: 'h1', number: 1,
    title: 'Claves de Inversión 2025',
    score: 9.2,
    hook: 'El error que comete el 99% de los inversores novatos en su primer año.',
    category: 'Finanzas',
    startMinutes: 4, startSeconds: 15, endMinutes: 5, endSeconds: 10,
    justification: 'Análisis histórico con estadísticas de rendimiento. Muy compartido entre audiencias financieras.',
    selected: false,
    sourceVideoName: 'Masterclass_Finanzas_2025.mp4',
    processedAt: Date.now() - 172800000,
    isNew: false,
    platform: 'TikTok',
    style: 'Informativo',
    sourceDuration: '1:12:30',
  },
  {
    id: 'h2', number: 2,
    title: 'Cómo escalar sin perder cultura',
    score: 8.7,
    hook: 'Pasamos de 5 a 50 personas en 6 meses. Casi destruimos la empresa.',
    category: 'Storytelling',
    startMinutes: 15, startSeconds: 20, endMinutes: 16, endSeconds: 30,
    justification: 'Historia de crecimiento con tensión emocional. Alto engagement por la vulnerabilidad del speaker.',
    selected: false,
    sourceVideoName: 'Masterclass_Finanzas_2025.mp4',
    processedAt: Date.now() - 172800000,
    isNew: false,
    platform: 'TikTok',
    style: 'Informativo',
    sourceDuration: '1:12:30',
  },
  {
    id: 'h3', number: 1,
    title: 'El framework para crear contenido viral',
    score: 9.5,
    hook: 'No necesitas millones de seguidores. Solo necesitas entender este patrón.',
    category: 'Educativo',
    startMinutes: 7, startSeconds: 0, endMinutes: 8, endSeconds: 15,
    justification: 'Promesa clara + framework accionable. Los contenidos de "cómo hacer" con frameworks concretos tienen alto ratio de guardado.',
    selected: false,
    sourceVideoName: 'Podcast_Marketing_Digital_EP42.mp4',
    processedAt: Date.now() - 604800000,
    isNew: false,
    platform: 'Instagram Reels',
    style: 'Educativo',
    sourceDuration: '45:20',
  },
  {
    id: 'h4', number: 2,
    title: 'Por qué el SEO está muriendo',
    score: 8.3,
    hook: 'Google acaba de cambiar las reglas del juego. Y la mayoría no se ha enterado.',
    category: 'Tech',
    startMinutes: 22, startSeconds: 45, endMinutes: 24, endSeconds: 0,
    justification: 'Tema polémico con toma de posición fuerte. Genera debate y comentarios. Ideal para LinkedIn.',
    selected: false,
    sourceVideoName: 'Podcast_Marketing_Digital_EP42.mp4',
    processedAt: Date.now() - 604800000,
    isNew: false,
    platform: 'Instagram Reels',
    style: 'Educativo',
    sourceDuration: '45:20',
  },
  {
    id: 'h5', number: 3,
    title: 'El truco de copywriting que duplicó mis ventas',
    score: 7.9,
    hook: 'Cambié una sola palabra en mi landing page y las conversiones se duplicaron.',
    category: 'Educativo',
    startMinutes: 33, startSeconds: 10, endMinutes: 34, endSeconds: 25,
    justification: 'Caso práctico con resultado cuantificable. Los "antes y después" con datos concretos generan curiosidad.',
    selected: false,
    sourceVideoName: 'Podcast_Marketing_Digital_EP42.mp4',
    processedAt: Date.now() - 604800000,
    isNew: false,
    platform: 'Instagram Reels',
    style: 'Educativo',
    sourceDuration: '45:20',
  },
  {
    id: 'h6', number: 1,
    title: 'Inteligencia artificial en la educación',
    score: 8.9,
    hook: 'En 5 años no reconocerás una clase universitaria. Te explico por qué.',
    category: 'Tech',
    startMinutes: 3, startSeconds: 30, endMinutes: 4, endSeconds: 50,
    justification: 'Predicción audaz sobre un tema que afecta a millones. Alto potencial de debate y compartidos.',
    selected: false,
    sourceVideoName: 'Entrevista_IA_Educacion_2025.mp4',
    processedAt: Date.now() - 2592000000,
    isNew: false,
    platform: 'LinkedIn',
    style: 'Informativo',
    sourceDuration: '58:15',
  },
  {
    id: 'h7', number: 2,
    title: 'El modelo de negocio del futuro',
    score: 7.5,
    hook: 'Las universidades que no se adapten desaparecerán en una década.',
    category: 'Inspiracional',
    startMinutes: 28, startSeconds: 0, endMinutes: 29, endSeconds: 30,
    justification: 'Declaración provocadora que genera reacción inmediata. Funciona bien como opener de debate en LinkedIn.',
    selected: false,
    sourceVideoName: 'Entrevista_IA_Educacion_2025.mp4',
    processedAt: Date.now() - 2592000000,
    isNew: false,
    platform: 'LinkedIn',
    style: 'Informativo',
    sourceDuration: '58:15',
  },
];